language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: pNtLkKJxlbdqNrG0jkDQlMdCfTvey4JtY64Pvptud3hS2sx2yBEyKTMxoBaUebF0M1zaphtqHVV75Y1GHCNL2tUDzmsv17RdOq+uPQq2dQlUy/G9aTWxhm9zRkdrM3wRhreBa9hgtvGftwQYbl242prELMrO4MsAfpQyE/PPHP7ZuXSPuy7+VORppdFnpP8+Jdp8V9so/xnzmttqbMCiQwKU7QR6MJ96ndE1H4RxsszsqkOTsyG3IQ6oX6U1eCxHesTer1vQzGIFtGxkWg09xAaTyR4w7VHHQUW3UxACSyflgn8nkLcFxbRkPlx9sab0OWE64FggcQYBCviiHL4v8n3rgM29xaqPWITllZ/B3kqa9gk46/NXcagfT5yIZ0Q0kywImU2jRDGC1PDI7D+pQVcATOURbyahGe+m8x3Ts/55IW9aLMBqWPj2tJ/OAkPKRodFRkiU4vbMDX0zlk7r+TXqOS14gt0/YFtqiUfeNJARtq+QVPQCrdCMLCP0qpSFLmB7nbMwRYH0P79gcxwoDuoQh8dVkb64QCbnJa6X9L0ZW6H2RHJxKnKP85A97JOGC6QwJLXoB7KReAr507wYXkai0LQICxX2HUjd8UzclWfQXpiFoH+QRmKRlStxOjliQDsgv0waaYwy19zrbcaKgECO+/C3E7rIo3+OnfGe87M=
  app: prework-deploy
  skip_cleanup: true
