language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: FjMnjDGBLN/a2A33FfPre6tcSP6vgyS0wNPYaDVh+p72KXd4tZD5uDgOxHIhrX1zurvcmyzNA3ArxY3FYS/LYV0NVKDFTAll6O3pSbx5Fc9ZfSb3e1ozMmH7BBOn0y9MsHl228CvCd9LbYJ5BlZwL8YQzJXy5+SxyBh2IN7yRRAvI8J+Uuwt0sjj0pPe/VtqvHkiy4NnClih1Vd7Z/SANQJ1fm9aB4GxOh7C6SSyVuSEhaavpUGXkBlH1gOB3KW2xA13k5srg9HvbnOJ53RVyV+eV40ErrF1mQWMG9jrH/z2iCsfbRnn1Z6pEXXo1L5DpW3JRbEdiN8uE4kbB040X8yhEG5IiyRbRZ4ja3x8Q1cZOr6coqtBnFDo/Ec90DHCCuazk/d+bK6Q39x9rYhkPPxGN0rooARp5SSlHRz6vq6o90r8I3rAPRk8E9YxQJFdXUSDu/HrP2825/cE0UM04TwpSIu2LJnPXyRpXEyxkfv4BEy0jxpyajA2GGJQkRAwT/LRB1RbXeMXnb2FMDTmQOODektl4+jQKnvr5e9O2JBe4qUR9VnSdR6ScIlYryK8Nnv5krQzd9sACWZ0YmjCgreQ8NAbB8salxIg9DraffjSlmx5djuAzyQ76S9OCJzyDvEXoWFbtpTxiwnFCuU3mVjJ7gwOddAfd9Zl94GXg7c=
  app: binary-challenge
  skip_cleanup: true
