language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: UXfIVjeOSCpKAxexgYt61vCnuk/mRhchvPZb05zkSJuKUNBbUidnTvNiRnGyEREfC+4mo+Xj5DkaBT7MtlGyDQ0qzcN5LR4AFARX6bDlIck6D/9Io15dvWxxKQZ9uADL4lpM7kYtfgdScn3I+dCbZLS8Ijq1XOpWFY9JFxTfoTS88xIgZn1i66/IZNHwOORtXdeBN2oYy1vmjcZsBOYTAWdlsm1/HOAdRbvhGJFfGkZEetVrQz0oRf06POISj+Utu2dFdwh5KrANxoJwyPm1bf3O4teTc14SqKmNwdTpyJsGSrrqfSpRztJX7Z8nmSpodm09aAqV8T4XGUVRpj6HO35wNoA3wFhhIm9gi0P44o2je6lcgfQLPshSwgwF5R3IAOJMBgujPlK97fJUTt0/jkWzrH1Gb7tZL1Xujm02xvf2KPxXoBbL9/3OREiBpl68fC+oDq1BKbdL6TDvI+lHXCtFRiNlWdl6zkEmhE72PRqNkvfG1Zs3uw5AQAqhQ1hZX71UXkFUtLbxfF7tKBrHeomDl3Ht49OZHFS8bs7gUgMPo6uJtgMZKZEzYqoa3DzxW+BDao2nclsHQlzpHygyslhslIpgE5Dvix70wytOFaeFfUftRMDbJ8QWsJE2XsJxV7Ng8+/cCXvVx/t1blWMtMIIbH7m83mdTSMZxyyShb8=
  app: binary-challenge
  skip_cleanup: true
